### ISSUE TITLE
BancaFinal - revLuzzardi

### ISSUE THREAD

**Issue by pluzzardi** [pedrocantarellicosta/ProjetoTCC#4]
1. Citação errada: (SEDGEWICK; K.WAYNE, 2011)

2. Wiki: Estrutura estranha - organizar

3. Falta de referências, pois  tem citações

4. Sem indentação?

5. Mostrar registradores?

6. Mostrar código em assembler?

7. Gerar código em Java, Python, C, C#, etc

**Comment by pedrocantarellicosta** [comment]
- Citação ja foi arrumada,
- Organização será melhorada assim que terminar de implementar a ferramenta.
- As referencias estão ajustadas no texto feito no LaTex
- A indentação é feita pelo usuário e não automática.
- A ferramenta tem intuito auxiliar e ajudar pessoas que não tem possuem conhecimento sobre lógica de programação, então penso que programação em baixo nível não iria ajudar nesse aprendizado.
