### ISSUE TITLE
SeminárioFinal_revAngelo

### ISSUE THREAD

**Issue by angelogluz** [pedrocantarellicosta/ProjetoTCC#5]
**Correções**
- [ ] Fazer comparativo com os sistemas similares
- [x] Alguns "Sistemas Similares" são referenciados (citados), outros não.
- [ ] Na documentação poderia constar tudo que o sistema suporta de estruturas
- [x] "Linguagem escolhida para o sistema foi o HTML, CSS e Javascript" --> retirar o "escolhida"
- [x] Colocar referências na mesma página da documentação
- [x] Habilitar a "exportação para Javascript"

**Considerações**
- Posso inserir comentários no código?
- Na forma como a documentação é apresentada, o sistema parece simples.
- O que falta implementar?
- Não poderia ter "exercícios" no sistema para o pessoal saber o que fazer? Ou dar dicas...
- Verificar as pontuações dos finais dos marcadores (Apresentação)
- Seria interessante poder gerar um código e enviar para os outros através de link ou fazer download e upload de código(Professor compartilhar código com alunos)
- Quem sabe muitos usuários poderem trabalhar juntos na criação?

**Comment by pedrocantarellicosta** [comment]
- Não foram implementados comentários nos códigos.
- Falta implementar a função ler para usuário poder utilizar input de dados.
- A função da ferramenta não é ter exercícios mas sim disponibilizar um local onde o usuário possa desenvolver qualquer exercício básico de lógica para tentar entender como se dá o fluxo de código desenvolvido.
- Foi desenvolvido uma maneira de upload de arquivo texto para ser compartilhado código entre usuários.
- Trabalho entre múltiplos usuários é uma boa ideia e esta sendo pensada a respeito. Pelo fato do pouco tempo para apresentação do trabalho, estou pensando em colocar como trabalho futuro.
